version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0
jobs:
  Deploy To Staging:
    docker:
      # specify the version you desire here
      - image: cibuilds/aws:latest
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/
      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            aws s3 cp public/ s3://nathanvale.dev --recursive && aws cloudfront create-invalidation --distribution-id E1MF21UE0533BK --paths /*

workflows:
  version: 2
  build:
    jobs:
      - cypress/install:
          name: 'Install & Validate Build'
          yarn: true
          build: 'yarn validate'
          post-steps:
            - persist_to_workspace:
                root: .
                paths:
                  - public
      - cypress/run:
          name: 'Run E2E Tests'
          requires:
            - Install & Validate Build
          parallel: true
          parallelism: 4
          group: 3 machines
          start: 'yarn serve'  # start server before running tests
          wait-on: 'http://localhost:9000'
      - Deploy To Staging:
          filters:
            branches:
              only: master
          requires:
            - Run E2E Tests
