version: 2.1
orbs:
  cypress: cypress-io/cypress@1.7.0
jobs:
  deploy:
    docker:
      # specify the version you desire here
      - image: cibuilds/aws:latest
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/
      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            aws s3 cp public/ s3://nathanvale.dev --recursive && aws cloudfront create-invalidation --distribution-id E1MF21UE0533BK --paths /*

workflows:
  version: 2
  build_and_deploy:
    jobs: # run a custom app build step
      - cypress/run:
          yarn: true
          build: 'yarn validate'  #
          start: 'yarn serve'  # start server before running tests
          wait-on: 'http://localhost:9000'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - cypress/run
